# -*- coding: utf-8 -*-
"""AssignmentForSnippetCompletion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kNsytZmAwjAtTJpXSKwiuHIhYPMgDZoF

# Assignment: Complete the Snippet

Shubh started building a basic Python Script which goes through the entire text of a particular book and mugs up all its words. After that it asks you for a word, goes over the times when this word came in the text and gives you the complete sentence in which it was used. You may choose to ask for as many such sentences as the number of occurences of the word.

He's managed to come up with the part where he loads the file into Memory. He also managed to come up with snippets of code which could potentially do something if completed, but he has many deadlines to look after and not enough caffeine to turn to code. Can you help him?
"""

File = open("HarryPotterAndTheSorcerersStone.txt",'r',encoding = 'UTF-8') #This helps in opening the file which is to be read

"""Next he makes a list of all the words present in the novel mapping them to their index(position) in the list of words (i.e. ListOfWords). This is done by mapping every word (a string) to a list (list of indices), and this is stored as a Dictionary (DictionaryoOfWords)



He makes use of the readlines() method which is used to extract all the lines from any text and the split() function which could be used to split any sentence into distinct words. The replace() method is used on strings to replace certain segments of the string with something else.
"""

DictionaryOfWords = {}         #Dictionary mapping every word to a list (of indices of the words' occurences)
Novel = []                     #List of all words in the order, in which they appear!



i = 0                   #Counter Variable to keep track of index of words

for line in File.readlines():     #Iterate over all lines present in the text
    
    #Look at Python's Conciseness!
    
    line = line.replace(".","").replace(",","").replace('?','').replace('!','').replace('[','').replace(']','')\
    .replace('(','').replace(')','').replace('%','').replace('/','')
      
    #COMPLETE THE CODE FROM HERE:
    
    #This would split the line into many different words, and iterate over these words
    
    for word in line.split(' '): 
                                                                             
        if word in DictionaryOfWords.keys():     #If the word is already present in the dictionary
                                                                             
            DictionaryOfWords[word].append(i)        #Add the index into the pre-existing list for this word
                                                                             
        else:
            DictionaryOfWords[word]=[i]        #Create a new list of indices for this word, with a single element
                                                                             
        
        Novel.append(word)        #Add the Word in the Novel's ordered list of words
                                                                             
        i+=1

"""That guy truly left a lot of work for you!

Now that you've done that, We have the words in the novel alongwith where they appeared in the text loaded into memory (Thanks to You!).

The Next Step would be to answer any queries the user may have.

To do this, we define the function GetQuery() which returns the word as well as the number of results the user wants to see (as a tuple):


"""

#COMPLETE THE CODE FROM HERE:

def GetQuery():
   
    word = input("Enter the word you have query for : ")        #Get Input from the user regarding what word s/he wants to query for

    Number = input("Enter the Number : ")      #Get Input from the user regarding how many results the user wants to see

    return (word,Number)                 #Return as output a tuple of the word and the Number of results

"""Now, We need a function which takes as input the index of any particular word and prints the words surrounding it as if they were in an actual sentence. 

This is done by iterating over the words surrounding it, and printing them with gaps in between. We also assume that this occurence isn't a boundary case and thus, the 10 words surronding it actually exist.
"""

def PrintContext(index):
    
    global Novel                          #Declares the list Novel as a Global Variable
    
    #COMPLETE THE CODE FROM HERE:
    
    for i in range(-5,6) :           #Define the range so that the task above is fulfilled
        
        print(Novel[index+i], end = ' ')          #Print the word (using List Indexing) with a space after that
        
    print('\n')

"""The result of the GetQuery() function will be passed into a second function which would take as input the word and the number of results to be displayed and do so!"""

def PrintResult(word, NumQuery):
  
    global DictionaryOfWords                #Allows us to use the Dictionary as a global variable
    
    #COMPLETE THE CODE FROM HERE:
    
    L = DictionaryOfWords[word] 
    
    for i in range(0,min(len(L),NumQuery)):
        
        PrintContext(L[i])             #Actually print the words surrounding the ith occurence of the given word

"""Finally, you need an infinite loop which runs until the user wants it to and asks for the next word (if the user wants to query more) or end the loop."""

while 1>0 :   
    
    Choice = input('Press Y in order to Continue with the next query or N to end. Please press Enter after entering your choice!')
    
    #COMPLETE THE CODE FROM HERE:
    
    if Choice=="Y":                     # If the user wants to query 
        a=GetQuery()
        PrintResult(a[0],int(a[1]))                        #Use some of the past defined function to do so
        
    else:
        
        break                                 #Else end the loo